version: '2'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    network_mode: host

  grafana:
    image: grafana/grafana:10.1.5
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

networks:
  loki:
